### ISSUE TITLE
group level smoothing

### ISSUE THREAD

**Issue by iqrashahzad14** [cpp-lln-lab/bidspm#995] opened 2023-04-29 19:14 UTC
I am doing group-level analysis with bidspm. The default conFWHM is 0. How can I change that?

`bidspm(bids_dir, output_dir, 'dataset', ...
       'participant_label', {'001','002','003','004','005'}, ...
       'action', 'stats', ...
       'preproc_dir', preproc_dir, ...
       'model_file', model_file,...
       'task', {taskName},...
       'space', {'IXI549Space'}, ...
       'fwhm', 6,...
       'ignore', {'qa','concat'},...
       'concatenate', false);`

**Comment by Remi-Gau** [comment] 2023-05-01 08:18
duplicate of #997 
closing

**Closed by Remi-Gau** 2023-05-01 08:18 UTC
