### ISSUE TITLE
[BUG] labels for concatenation of 4-D images are not consistent

### ISSUE THREAD

**Issue by iqrashahzad14** [cpp-lln-lab/bidspm#1062] opened 2023-06-20 12:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

- Linux Ubuntu 22.04 "jammy jellyfish"
- Mac OS Version 12 "monterey"

### SPM 12 version

- [X] 7771
- [ ] 7487
- [ ] 7219

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

- MATLAB 2017a
- Octave 4.2.2

### bidspm version

v3.0.0

### Expected Behavior

When I do 'concatenate', true (considering one beta per run for each condition)

the tsv file should have the number of runs and the conditions equal to the number of runs. However this is not consistent. My dataset has 10 runs except for one subject, which has 9 runs.  the tsv label fold consisted of 8 runs of condition A and 12 runs of condition B for this subject. 
And this behaviour is not consistent across tasks.
```
folds	labels
1	visual_horizontal*bf(1)
1	visual_horizontal*bf(1)
1	visual_horizontal*bf(1)
1	visual_horizontal*bf(1)
1	visual_horizontal*bf(1)
1	visual_horizontal*bf(1)
1	visual_horizontal*bf(1)
1	visual_horizontal*bf(1)
1	visual_horizontal*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
1	visual_vertical*bf(1)
```
```
folds	labels
1	handUp_pinkyThumb*bf(1)
1	handUp_pinkyThumb*bf(1)
1	handUp_pinkyThumb*bf(1)
1	handUp_pinkyThumb*bf(1)
1	handUp_pinkyThumb*bf(1)
1	handUp_pinkyThumb*bf(1)
1	handUp_pinkyThumb*bf(1)
1	handUp_pinkyThumb*bf(1)
1	handUp_pinkyThumb*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
1	handUp_fingerWrist*bf(1)
```

### Current Behavior & Error message

```matlab
% copy the error you got below
% before the three backticks (```)




```

**Comment by iqrashahzad14** [comment] 2023-06-20 15:51
Sending you on discord?

**Comment by Remi-Gau** [comment] 2023-06-20 17:35
Extracted the code that generate the content of the tsv from its workflow to test it on your SPM.mat and bids model.


```matlab
load('SPM.mat', 'SPM');
model = BidsModel('file', 'model-visual_smdl.json');

node = model.get_root_node();

try
  contrasts = specifyContrasts(SPM, model, node.Name);
catch
  msg = 'Could not find dummy contrasts in the BIDS stats model.';
  error(msg);
end

betaMaps = {};
tMaps = {};

for iContrast = 1:length(contrasts)
    
    msg = sprintf('\n\t%s', contrasts(iContrast).name);
    betasIndices = find(contrasts(iContrast).C);
    
    if numel(betasIndices) > 1
        msg = sprintf(['Supposed to concatenate one beta image per contrast.' ...
            '\nSkipping: %s'], contrasts(iContrast).name);
        warning(msg);
        continue
    end
    
    % for this beta image we identify
    % - which run it came from
    % - the exact condition name stored in the SPM.mat
    % so they can be saved in a tsv for for "label" and "fold" for MVPA
    for iSess = 1:numel(SPM.Sess)
        tmp(iSess) = ismember(betasIndices, SPM.Sess(iSess).col); %#ok<*AGROW>
    end
    runs(iContrast, 1) = find(any(tmp, 1));
    clear tmp;
    
    parts = strsplit(SPM.xX.name{betasIndices}, ' ');
    conditions{iContrast, 1} = strjoin(parts(2:end), ' ');
    
    fileName = sprintf('beta_%04d.nii', betasIndices);
    betaMaps{iContrast, 1} = [fileName, ',1'];
    
    fileName = sprintf('spmT_%04d.nii', iContrast);
    tMaps{iContrast, 1} = [fileName, ',1'];
    
end

conditions
betaMaps
```

And so far I cannot reproduce this issue:

```
conditions =
  18×1 cell array
    {'visual_horizontal*bf(1)'}
    {'visual_horizontal*bf(1)'}
    {'visual_horizontal*bf(1)'}
    {'visual_horizontal*bf(1)'}
    {'visual_horizontal*bf(1)'}
    {'visual_horizontal*bf(1)'}
    {'visual_horizontal*bf(1)'}
    {'visual_horizontal*bf(1)'}
    {'visual_horizontal*bf(1)'}
    {'visual_vertical*bf(1)'  }
    {'visual_vertical*bf(1)'  }
    {'visual_vertical*bf(1)'  }
    {'visual_vertical*bf(1)'  }
    {'visual_vertical*bf(1)'  }
    {'visual_vertical*bf(1)'  }
    {'visual_vertical*bf(1)'  }
    {'visual_vertical*bf(1)'  }
    {'visual_vertical*bf(1)'  }
betaMaps =
  18×1 cell array
    {'beta_0001.nii,1'}
    {'beta_0009.nii,1'}
    {'beta_0017.nii,1'}
    {'beta_0025.nii,1'}
    {'beta_0033.nii,1'}
    {'beta_0041.nii,1'}
    {'beta_0049.nii,1'}
    {'beta_0057.nii,1'}
    {'beta_0065.nii,1'}
    {'beta_0002.nii,1'}
    {'beta_0010.nii,1'}
    {'beta_0018.nii,1'}
    {'beta_0026.nii,1'}
    {'beta_0034.nii,1'}
    {'beta_0042.nii,1'}
    {'beta_0050.nii,1'}
    {'beta_0058.nii,1'}
    {'beta_0066.nii,1'}
```

**Comment by Remi-Gau** [comment] 2023-06-20 17:38
it is strange you are getting a column of ones in your tsv:
mine looks like this.

```
folds	labels
1	visual_horizontal*bf(1)
2	visual_horizontal*bf(1)
3	visual_horizontal*bf(1)
4	visual_horizontal*bf(1)
5	visual_horizontal*bf(1)
6	visual_horizontal*bf(1)
7	visual_horizontal*bf(1)
8	visual_horizontal*bf(1)
9	visual_horizontal*bf(1)
1	visual_vertical*bf(1)
2	visual_vertical*bf(1)
3	visual_vertical*bf(1)
4	visual_vertical*bf(1)
5	visual_vertical*bf(1)
6	visual_vertical*bf(1)
7	visual_vertical*bf(1)
8	visual_vertical*bf(1)
9	visual_vertical*bf(1)
```

**Comment by Remi-Gau** [comment] 2023-06-20 17:40
Same with the other tasks:

```
conditions =
  18×1 cell array
    {'handUp_pinkyThumb*bf(1)' }
    {'handUp_pinkyThumb*bf(1)' }
    {'handUp_pinkyThumb*bf(1)' }
    {'handUp_pinkyThumb*bf(1)' }
    {'handUp_pinkyThumb*bf(1)' }
    {'handUp_pinkyThumb*bf(1)' }
    {'handUp_pinkyThumb*bf(1)' }
    {'handUp_pinkyThumb*bf(1)' }
    {'handUp_pinkyThumb*bf(1)' }
    {'handUp_fingerWrist*bf(1)'}
    {'handUp_fingerWrist*bf(1)'}
    {'handUp_fingerWrist*bf(1)'}
    {'handUp_fingerWrist*bf(1)'}
    {'handUp_fingerWrist*bf(1)'}
    {'handUp_fingerWrist*bf(1)'}
    {'handUp_fingerWrist*bf(1)'}
    {'handUp_fingerWrist*bf(1)'}
    {'handUp_fingerWrist*bf(1)'}
```

**Comment by iqrashahzad14** [comment] 2023-06-23 11:06
everything is okay now! The tsv with the new update includes number from 1 to 9. The output from the previous version included only ones.

**Comment by Remi-Gau** [comment] 2023-06-23 13:03
woohoo
will close this then

**Closed by Remi-Gau** 2023-06-23 13:03 UTC
Labels: bug :bug:
